### Import relative libraries

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
nestead_list = [[1,2],[3,4],[5,6]]

In [8]:
nestead_list

[[1, 2], [3, 4], [5, 6]]

In [9]:
np.array(nestead_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(2)

array([0.71651867, 0.98454258])

In [27]:
np.random.rand(3,4)

array([[0.28503669, 0.41024565, 0.72122991, 0.14948588],
       [0.3588427 , 0.62023939, 0.11307305, 0.80090145],
       [0.34155559, 0.60036925, 0.43846079, 0.06391327]])

In [28]:
np.random.randn(5,5)

array([[ 0.44821272, -1.35453922, -1.35171891,  0.49795408, -0.42095591],
       [ 1.09517905, -2.11523631,  0.80130498,  1.24812566,  0.32939661],
       [-0.39538016,  0.31851877,  1.99628991,  0.39852478,  0.03763583],
       [ 0.66540088,  0.86813205, -0.33905367,  0.25514006, -0.73187747],
       [-1.91873597,  1.54123447,  0.44600341,  0.04613978,  1.12028409]])

In [29]:
np.random.randint(1,100)

37

In [30]:
np.random.randint(1,100,10)

array([19, 39, 96, 22, 49, 49, 24, 28, 37, 49])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [33]:
arr = np.arange(25)

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [37]:
arr.shape

(25,)

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr = arr.reshape(5,5)

In [41]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr 

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [44]:
ranarr.max()

43

In [45]:
ranarr.min()

1

In [47]:
ranarr.mean()

25.3

In [48]:
ranarr.argmax()

7

In [49]:
ranarr.argmin()

5

In [56]:
ranarr.dtype

dtype('int32')

In [57]:
myarr = np.random.rand(4)

In [58]:
myarr

array([0.04666566, 0.97375552, 0.23277134, 0.09060643])

In [59]:
myarr.dtype

dtype('float64')