# Import the relevant libraries

In [1]:
import numpy as np

## Declaring scalar, vectors, and matrices

### Scalars

In [2]:
s = 5

In [3]:
s

5

### Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

### Matrices

In [6]:
m = np.array([[5, 12, 6],[-3, 0, 14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [10]:
type(s)

int

In [12]:
type(v)

numpy.ndarray

In [14]:
type(m)

numpy.ndarray

In [16]:
s_array = np.array(5)
s_array

array(5)

In [18]:
type(s_array)

numpy.ndarray

### Data shapes

In [20]:
m.shape

(2, 3)

In [22]:
v.shape

(3,)

In [24]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [27]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [30]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [32]:
s_array.shape

()

### Creating a column vector