# Import the relevant libraries

In [2]:
import numpy as np

### Creating a tensor

In [4]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [8]:
t = np.array([m1,m2])

In [10]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Creating its shape

In [12]:
t.shape

(2, 2, 3)

### Manually creating a tensor - it is possible but pay attention to the square brackets