### Import relevant libraries

In [2]:
import numpy as np

### Matrix transpose

In [5]:
A = np.array([[12,2,3,4],[45,5,6,7]])
A

array([[12,  2,  3,  4],
       [45,  5,  6,  7]])

In [6]:
A.T

array([[12, 45],
       [ 2,  5],
       [ 3,  6],
       [ 4,  7]])

In [7]:
B = np.array([[2,3,4],[6,7,8]])
B

array([[2, 3, 4],
       [6, 7, 8]])

In [8]:
B.T

array([[2, 6],
       [3, 7],
       [4, 8]])

In [9]:
C = np.array([[5,6],[7,8]])

C

array([[5, 6],
       [7, 8]])

In [10]:
C.T

array([[5, 7],
       [6, 8]])

In [11]:
A.shape

(2, 4)

In [12]:
B.shape

(2, 3)

In [13]:
C.shape

(2, 2)

### Transposing Vectors

In [18]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [19]:
x.T

array([1, 2, 3])

In [20]:
x.shape

(3,)

In [22]:
x_reshape = x.reshape(1,3)
x_reshape

array([[1, 2, 3]])

In [23]:
x_reshape.T

array([[1],
       [2],
       [3]])