In [2]:
import numpy as np

## DataTypes & Attributs

# NumPyS main datatype is ndarray

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3 = np.array([[[1,2,3],
              [4,5,6,],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape


(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
a1.size

3

In [18]:
a2.size

6

In [19]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a3.size

18

In [21]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### ndarray is a unversal data type
#### ndarray = 3 is a tensor

In [22]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)

In [23]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### 2.Creating arrays

In [24]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int32')

In [26]:
ones = np.ones((2,3))

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [29]:
type(ones)

numpy.ndarray

In [30]:
zeros = np.zeros((2,3))

In [31]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
range_array = np.arange(0,10,2)

In [33]:
range_array

array([0, 2, 4, 6, 8])

In [35]:
random_array = np.random.randint(0, 10, size=(3,5))

In [36]:
random_array

array([[0, 2, 9, 1, 9],
       [2, 3, 6, 9, 0],
       [6, 2, 7, 4, 7]])

In [37]:
random_array.size

15

In [38]:
random_array.shape

(3, 5)

In [40]:
random_array_2 = np.random.random((5,3))

In [41]:
random_array_2

array([[0.34440426, 0.85747428, 0.80967918],
       [0.55082997, 0.59975442, 0.9923055 ],
       [0.48967725, 0.21394951, 0.57264577],
       [0.82642724, 0.94328129, 0.67376207],
       [0.55796584, 0.64412144, 0.82450231]])

In [42]:
random_array_2.shape

(5, 3)

In [43]:
random_array_2.size

15

In [44]:
random_array_2.dtype

dtype('float64')

In [45]:
type(random_array_2)

numpy.ndarray

In [46]:
random_array_3 = np.random.rand(5,3)

In [47]:
random_array_3

array([[0.1253829 , 0.58234657, 0.59487445],
       [0.40364111, 0.20622211, 0.64177864],
       [0.09523778, 0.23787888, 0.28050398],
       [0.32818283, 0.68427141, 0.05272282],
       [0.57840141, 0.2652037 , 0.35108724]])

In [48]:
# Pseudo-random numbers
np.random.seed()

In [49]:
random_array_3.dtype

dtype('float64')

In [50]:
random_array_3.size

15

In [51]:
random_array_3.ndim

2

In [52]:
type(random_array_3)

numpy.ndarray

In [53]:
random_array_3.shape

(5, 3)

In [61]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size= (5,3))

In [62]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [59]:
random_array_4.shape

(5, 3)

In [63]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

### 3.Viewing arrays and matrices

In [64]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a1

array([1, 2, 3])

In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [68]:
a1[0]

1

In [69]:
a2[0]

array([1. , 2. , 3.3])

In [70]:
a3.shape

(2, 3, 3)

In [71]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a2.shape


(2, 3)

In [73]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [74]:
a2[1]

array([4. , 5. , 6.5])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [78]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [79]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [83]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])